version: '3'
services:
  api:
    build: .
    container_name: giftapp-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
    networks:
      - fluxs-landing_app_network
networks:
  fluxs-landing_app_network:
    external: true
