version: '3'
services:
  api:
    build: .
    container_name: giftapp-api
    ports:
      - "3000:3000"
    networks:
      - fluxs-landing_app_network

networks:
  fluxs-landing_app_network:
    external: true